name: 'Linear release notifs'
description: 'A small GitHub action to update Linear tickets when pushing to a particular branch'
inputs:
  linear-api-key:
    description: 'Linear API key'
    required: true
  discord-webhook-url:
    description: 'Discord Webhook URL'
    required: true
outputs: {}
runs:
  using: 'node16'
  main: 'dist/action.global.js'
