name: "Linear release notifs"
description: "A small GitHub action to update Linear tickets when pushing to a particular branch"
inputs: {}
outputs: {}
runs:
  using: "node16"
  main: "dist/action.global.js"
