on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: curiousaddys/linear-release-notifs@main
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
